import type { CompanyProfile } from "@/lib/types";

/**
 * Seeded demo brands.
 *
 * Every figure here is invented. It is shaped to be plausible for an Indian D2C
 * brand in the ₹2–20 crore revenue band, but it is not derived from any real
 * company and must never be presented as market evidence. The UI labels it as
 * simulated everywhere it appears.
 */

export const AURA_SKINCARE: CompanyProfile = {
  id: "aura-skincare",
  name: "Aura Skincare",
  industry: "Beauty & Personal Care",
  businessModel: "d2c-ecommerce",
  annualRevenueINR: 80_000_000,
  monthlyPaidSpendINR: 600_000,
  aovINR: 1_850,
  grossMarginPct: 68,
  repeatPurchaseRatePct: 23,
  primarySalesChannel: "Own Shopify store",
  geography: "India — metro & tier-1",
  marketingTeamSize: 2,
  isDemo: true,
  notes:
    "Two-person marketing team. Founder signs off on the monthly media budget and asks for the reasoning every cycle.",
  fieldSources: {
    name: "demo",
    industry: "demo",
    businessModel: "demo",
    annualRevenueINR: "demo",
    monthlyPaidSpendINR: "demo",
    aovINR: "demo",
    grossMarginPct: "demo",
    repeatPurchaseRatePct: "demo",
    primarySalesChannel: "demo",
    geography: "demo",
    marketingTeamSize: "demo",
    channels: "demo",
    segments: "demo",
    repeatCustomerCacINR: "inferred",
  },
  channels: [
    {
      id: "meta",
      name: "Meta Ads",
      role: "demand-generation",
      monthlySpendINR: 300_000,
      cacINR: 915,
      roas: 3.4,
      conversionRatePct: 1.9,
      impressionSharePct: 42,
      headroom: 0.72,
      costElasticity: 0.42,
      dataConfidence: 0.88,
    },
    {
      id: "google",
      name: "Google Ads",
      role: "intent-capture",
      monthlySpendINR: 180_000,
      cacINR: 1_310,
      roas: 4.8,
      conversionRatePct: 3.6,
      impressionSharePct: 89,
      headroom: 0.15,
      costElasticity: 0.55,
      dataConfidence: 0.86,
    },
    {
      id: "retention",
      name: "Retention / CRM",
      role: "repeat-conversion",
      monthlySpendINR: 60_000,
      cacINR: 460,
      roas: 6.2,
      conversionRatePct: 5.4,
      impressionSharePct: 12,
      headroom: 0.83,
      costElasticity: 0.3,
      dataConfidence: 0.74,
    },
    {
      id: "influencer",
      name: "Influencer",
      role: "brand-amplification",
      monthlySpendINR: 60_000,
      cacINR: 1_520,
      roas: 2.05,
      conversionRatePct: 1.1,
      impressionSharePct: 30,
      headroom: 0.55,
      costElasticity: 0.45,
      dataConfidence: 0.52,
    },
  ],
  segments: [
    {
      id: "aura-repeat",
      name: "Repeat Skincare Buyers",
      description:
        "Bought at least twice in the last 9 months. Strong routine adherence, low discount dependency.",
      estimatedSize: 18_400,
      historicalCacINR: 720,
      repeatRatePct: 41,
      aovINR: 1_980,
      grossMarginPct: 70,
      conversionPropensity: 0.78,
      reachability: 0.85,
      channelAffinity: { meta: 0.9, google: 0.55, retention: 0.95, influencer: 0.4 },
      dataConfidence: 0.86,
    },
    {
      id: "aura-high-intent",
      name: "High-Intent First-Time Buyers",
      description:
        "Category-aware prospects searching for specific actives. Converts on proof, not on discount.",
      estimatedSize: 31_200,
      historicalCacINR: 1_050,
      repeatRatePct: 18,
      aovINR: 1_850,
      grossMarginPct: 66,
      conversionPropensity: 0.62,
      reachability: 0.92,
      channelAffinity: { meta: 0.72, google: 0.94, retention: 0.15, influencer: 0.68 },
      dataConfidence: 0.79,
    },
    {
      id: "aura-lapsed",
      name: "Lapsed Customers 90–180 Days",
      description:
        "Bought once, fell out of the routine. Reactivation is cheap but the window closes after ~180 days.",
      estimatedSize: 12_600,
      historicalCacINR: 460,
      repeatRatePct: 28,
      aovINR: 1_720,
      grossMarginPct: 67,
      conversionPropensity: 0.55,
      reachability: 0.7,
      channelAffinity: { meta: 0.65, google: 0.2, retention: 0.98, influencer: 0.18 },
      dataConfidence: 0.71,
      isReactivation: true,
    },
  ],
  campaignHistory: [
    { month: "Jun", spendINR: 520_000, revenueINR: 1_820_000, blendedCacINR: 1_140, roas: 3.5 },
    { month: "Jul", spendINR: 560_000, revenueINR: 1_960_000, blendedCacINR: 1_112, roas: 3.5 },
    {
      month: "Aug",
      spendINR: 600_000,
      revenueINR: 2_180_000,
      blendedCacINR: 1_070,
      roas: 3.63,
      note: "Retention pilot launched mid-month.",
    },
  ],
};

export const LOOM_AND_LINE: CompanyProfile = {
  id: "loom-and-line",
  name: "Loom & Line Apparel",
  industry: "Apparel & Accessories",
  businessModel: "omnichannel-retail",
  annualRevenueINR: 140_000_000,
  monthlyPaidSpendINR: 900_000,
  aovINR: 2_650,
  grossMarginPct: 54,
  repeatPurchaseRatePct: 17,
  primarySalesChannel: "Own store + marketplace",
  geography: "India — pan-India, metro weighted",
  marketingTeamSize: 3,
  isDemo: true,
  notes:
    "Seasonal drops. Creator-led discovery carries a real share of demand, which changes the channel argument entirely.",
  fieldSources: {
    name: "demo",
    industry: "demo",
    businessModel: "demo",
    annualRevenueINR: "demo",
    monthlyPaidSpendINR: "demo",
    aovINR: "demo",
    grossMarginPct: "demo",
    repeatPurchaseRatePct: "demo",
    primarySalesChannel: "demo",
    geography: "demo",
    marketingTeamSize: "demo",
    channels: "demo",
    segments: "demo",
    repeatCustomerCacINR: "inferred",
  },
  channels: [
    {
      id: "meta",
      name: "Meta Ads",
      role: "demand-generation",
      monthlySpendINR: 400_000,
      cacINR: 1_480,
      roas: 2.9,
      conversionRatePct: 1.4,
      impressionSharePct: 61,
      headroom: 0.44,
      costElasticity: 0.46,
      dataConfidence: 0.84,
    },
    {
      id: "google",
      name: "Google Ads",
      role: "intent-capture",
      monthlySpendINR: 250_000,
      cacINR: 1_690,
      roas: 3.4,
      conversionRatePct: 2.7,
      impressionSharePct: 48,
      headroom: 0.58,
      costElasticity: 0.38,
      dataConfidence: 0.81,
    },
    {
      id: "retention",
      name: "Retention / CRM",
      role: "repeat-conversion",
      monthlySpendINR: 70_000,
      cacINR: 690,
      roas: 4.4,
      conversionRatePct: 3.1,
      impressionSharePct: 14,
      headroom: 0.62,
      costElasticity: 0.34,
      dataConfidence: 0.63,
    },
    {
      id: "influencer",
      name: "Influencer",
      role: "brand-amplification",
      monthlySpendINR: 180_000,
      cacINR: 1_260,
      roas: 3.6,
      conversionRatePct: 1.8,
      impressionSharePct: 25,
      headroom: 0.7,
      costElasticity: 0.4,
      dataConfidence: 0.68,
    },
  ],
  segments: [
    {
      id: "loom-drop-followers",
      name: "Drop Followers",
      description:
        "Opted into launch alerts, buys within 72 hours of a drop. Small but exceptionally responsive.",
      estimatedSize: 9_800,
      historicalCacINR: 640,
      repeatRatePct: 38,
      aovINR: 3_100,
      grossMarginPct: 56,
      conversionPropensity: 0.81,
      reachability: 0.78,
      channelAffinity: { meta: 0.86, google: 0.3, retention: 0.94, influencer: 0.88 },
      dataConfidence: 0.8,
    },
    {
      id: "loom-workwear",
      name: "Workwear Switchers",
      description:
        "Searching for formal and semi-formal basics. High intent, price-comparison heavy.",
      estimatedSize: 44_500,
      historicalCacINR: 1_620,
      repeatRatePct: 14,
      aovINR: 2_480,
      grossMarginPct: 52,
      conversionPropensity: 0.58,
      reachability: 0.9,
      channelAffinity: { meta: 0.6, google: 0.92, retention: 0.12, influencer: 0.45 },
      dataConfidence: 0.76,
    },
    {
      id: "loom-gifting",
      name: "Gifting Buyers",
      description:
        "Seasonal, low repeat, high AOV. Demand appears and disappears with the festive calendar.",
      estimatedSize: 27_300,
      historicalCacINR: 1_910,
      repeatRatePct: 8,
      aovINR: 3_450,
      grossMarginPct: 50,
      conversionPropensity: 0.49,
      reachability: 0.83,
      channelAffinity: { meta: 0.74, google: 0.66, retention: 0.2, influencer: 0.7 },
      dataConfidence: 0.6,
    },
  ],
  campaignHistory: [
    { month: "Jun", spendINR: 820_000, revenueINR: 2_460_000, blendedCacINR: 1_570, roas: 3.0 },
    { month: "Jul", spendINR: 880_000, revenueINR: 2_640_000, blendedCacINR: 1_598, roas: 3.0 },
    {
      month: "Aug",
      spendINR: 900_000,
      revenueINR: 2_880_000,
      blendedCacINR: 1_524,
      roas: 3.2,
      note: "Monsoon drop over-indexed on creator content.",
    },
  ],
};

export const CRAVEBITE_FOODS: CompanyProfile = {
  id: "cravebite-foods",
  name: "CraveBite Foods",
  industry: "Packaged Foods & Snacks",
  businessModel: "subscription",
  annualRevenueINR: 42_000_000,
  monthlyPaidSpendINR: 350_000,
  aovINR: 740,
  grossMarginPct: 62,
  repeatPurchaseRatePct: 44,
  primarySalesChannel: "Own store (subscription) + quick commerce",
  geography: "India — Bengaluru, Mumbai, NCR",
  marketingTeamSize: 1,
  isDemo: true,
  notes:
    "Low AOV, very high repeat. One marketer. The entire business case lives in second and third orders, not the first.",
  fieldSources: {
    name: "demo",
    industry: "demo",
    businessModel: "demo",
    annualRevenueINR: "demo",
    monthlyPaidSpendINR: "demo",
    aovINR: "demo",
    grossMarginPct: "demo",
    repeatPurchaseRatePct: "demo",
    primarySalesChannel: "demo",
    geography: "demo",
    marketingTeamSize: "demo",
    channels: "demo",
    segments: "demo",
    repeatCustomerCacINR: "demo",
  },
  channels: [
    {
      id: "meta",
      name: "Meta Ads",
      role: "demand-generation",
      monthlySpendINR: 160_000,
      cacINR: 540,
      roas: 2.1,
      conversionRatePct: 2.4,
      impressionSharePct: 38,
      headroom: 0.68,
      costElasticity: 0.4,
      dataConfidence: 0.82,
    },
    {
      id: "google",
      name: "Google Ads",
      role: "intent-capture",
      monthlySpendINR: 70_000,
      cacINR: 810,
      roas: 2.6,
      conversionRatePct: 3.1,
      impressionSharePct: 71,
      headroom: 0.29,
      costElasticity: 0.48,
      dataConfidence: 0.7,
    },
    {
      id: "retention",
      name: "Retention / CRM",
      role: "repeat-conversion",
      monthlySpendINR: 90_000,
      cacINR: 190,
      roas: 7.8,
      conversionRatePct: 8.9,
      impressionSharePct: 9,
      headroom: 0.76,
      costElasticity: 0.26,
      dataConfidence: 0.88,
    },
    {
      id: "influencer",
      name: "Influencer",
      role: "brand-amplification",
      monthlySpendINR: 30_000,
      cacINR: 980,
      roas: 1.7,
      conversionRatePct: 0.9,
      impressionSharePct: 22,
      headroom: 0.6,
      costElasticity: 0.48,
      dataConfidence: 0.44,
    },
  ],
  segments: [
    {
      id: "crave-subscribers",
      name: "Active Subscribers",
      description:
        "On a recurring plan. Churn, not acquisition, is the number that decides the year.",
      estimatedSize: 14_100,
      historicalCacINR: 210,
      repeatRatePct: 72,
      aovINR: 820,
      grossMarginPct: 64,
      conversionPropensity: 0.86,
      reachability: 0.93,
      channelAffinity: { meta: 0.5, google: 0.18, retention: 0.99, influencer: 0.22 },
      dataConfidence: 0.9,
    },
    {
      id: "crave-trial",
      name: "Trial Pack Buyers",
      description:
        "Bought a single trial pack. Converting them to a subscription is where the margin is.",
      estimatedSize: 38_900,
      historicalCacINR: 470,
      repeatRatePct: 31,
      aovINR: 620,
      grossMarginPct: 58,
      conversionPropensity: 0.64,
      reachability: 0.88,
      channelAffinity: { meta: 0.88, google: 0.46, retention: 0.8, influencer: 0.5 },
      dataConfidence: 0.83,
    },
    {
      id: "crave-office",
      name: "Office Pantry Buyers",
      description:
        "Bulk orders for workplaces. Larger baskets, longer decision cycle, weak repeat as individuals.",
      estimatedSize: 6_400,
      historicalCacINR: 1_240,
      repeatRatePct: 22,
      aovINR: 2_900,
      grossMarginPct: 55,
      conversionPropensity: 0.41,
      reachability: 0.56,
      channelAffinity: { meta: 0.35, google: 0.86, retention: 0.3, influencer: 0.15 },
      dataConfidence: 0.55,
    },
  ],
  campaignHistory: [
    { month: "Jun", spendINR: 310_000, revenueINR: 1_050_000, blendedCacINR: 690, roas: 3.4 },
    { month: "Jul", spendINR: 330_000, revenueINR: 1_160_000, blendedCacINR: 664, roas: 3.5 },
    {
      month: "Aug",
      spendINR: 350_000,
      revenueINR: 1_290_000,
      blendedCacINR: 641,
      roas: 3.7,
      note: "Subscription win-back flow rebuilt.",
    },
  ],
};

export const DEMO_COMPANIES: CompanyProfile[] = [
  AURA_SKINCARE,
  LOOM_AND_LINE,
  CRAVEBITE_FOODS,
];

export function getDemoCompany(id: string): CompanyProfile | undefined {
  return DEMO_COMPANIES.find((c) => c.id === id);
}

/** Deep clone so a loaded company can be edited without mutating the seed. */
export function cloneCompany(company: CompanyProfile): CompanyProfile {
  return JSON.parse(JSON.stringify(company)) as CompanyProfile;
}

/** An empty profile for users who want to type their own context. */
export function emptyCompany(): CompanyProfile {
  return {
    id: `custom-${Date.now()}`,
    name: "",
    industry: "",
    businessModel: "d2c-ecommerce",
    annualRevenueINR: 0,
    monthlyPaidSpendINR: 0,
    aovINR: 0,
    grossMarginPct: 0,
    repeatPurchaseRatePct: 0,
    primarySalesChannel: "",
    geography: "India",
    marketingTeamSize: 0,
    channels: [],
    segments: [],
    campaignHistory: [],
    fieldSources: {},
    isDemo: false,
  };
}
